version: '3'

services:
  db:
    image: postgres:12
    container_name: ${DATABASE_CONTAINER}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./database/pagila-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/pagila-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    command: postgres -c max_locks_per_transaction=2000
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  graphql:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    container_name: ${HASURA_CONTAINER}
    restart: unless-stopped
    ports:
      - ${HASURA_PORT}:8080
    volumes:
      - ./${HASURA_SETTING_FOLDER}/migrations:/hasura-migrations
      - ./${HASURA_SETTING_FOLDER}/metadata:/hasura-metadata
    depends_on:
      - db
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_CONTAINER}:${DATABASE_PORT}/${DATABASE_NAME}
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET}
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: admin
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_CUSTOM_API_URL: ${HASURA_CUSTOM_API_URL}

volumes:
  data:
